
package perpustakaan;

import perpustakaan.logic.BukuCrudLogic;
import javax.swing.JFrame;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author roide
 */
public class BukuCrudAdmin extends JFrame {

    private BukuCrudLogic logicBuku;

    public BukuCrudAdmin() {
        setTitle("Data Buku Perpustakaan");
        logicBuku = new BukuCrudLogic();
        initComponents();
        tampilkanData();

    };

    private void tampilkanData() {
        DefaultTableModel model = logicBuku.getTableModel();
        TabelBuku.setModel(model);
    }

    private void tambahData(String judul, String idKategori, String pengarang, String penerbit, String tahunTerbit,
            String isbn, String stok) {
        logicBuku.tambahBuku(judul, idKategori, pengarang, penerbit, tahunTerbit, isbn, stok);
        tampilkanData();
    }

    /**
     * Creates new form TampilanUser
     */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        tambahBtn = new javax.swing.JButton();
        kategoriBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelBuku = new javax.swing.JTable();
        editBtn = new javax.swing.JButton();
        simpanBtn = new javax.swing.JButton();
        LogoutBtn = new javax.swing.JButton();
        judulBukuInput = new javax.swing.JTextField();
        pengarangInput = new javax.swing.JTextField();
        penerbitInput = new javax.swing.JTextField();
        judulBukuLabel = new javax.swing.JLabel();
        kategoriLabel = new javax.swing.JLabel();
        pengarangLabel = new javax.swing.JLabel();
        penerbitLabel = new javax.swing.JLabel();
        isbnLabel = new javax.swing.JLabel();
        isbnInput = new javax.swing.JTextField();
        stokLabel = new javax.swing.JLabel();
        stokInput = new javax.swing.JTextField();
        kategoriInput = new javax.swing.JComboBox<>();
        tahunTerbitLabel = new javax.swing.JLabel();
        tahunTerbitInput = new javax.swing.JTextField();
        userBtn = new javax.swing.JButton();
        hapusBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Admin Buku Manager");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setSize(new java.awt.Dimension(1024, 768));
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        tambahBtn.setBackground(new java.awt.Color(59, 113, 202));
        tambahBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        tambahBtn.setForeground(new java.awt.Color(255, 255, 255));
        tambahBtn.setText("Tambah");
        tambahBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 41;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 113, 0, 0);
        getContentPane().add(tambahBtn, gridBagConstraints);

        kategoriBtn.setBackground(new java.awt.Color(220, 76, 100));
        kategoriBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        kategoriBtn.setForeground(new java.awt.Color(255, 255, 255));
        kategoriBtn.setText("Kategori");
        kategoriBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        kategoriBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 37;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 29, 0, 0);
        getContentPane().add(kategoriBtn, gridBagConstraints);

        TabelBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Judul Buku", "Pengarang", "Penerbit", "Kategori", "ISBN", "Stok", "Dipinjam", "Tersedia"
            }
        ));
        TabelBuku.setAlignmentX(0.0F);
        TabelBuku.setAlignmentY(0.0F);
        TabelBuku.setShowGrid(true);
        jScrollPane1.setViewportView(TabelBuku);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 21;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 1206;
        gridBagConstraints.ipady = -418;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(55, 15, 21, 15);
        getContentPane().add(jScrollPane1, gridBagConstraints);

        editBtn.setBackground(new java.awt.Color(228, 161, 27));
        editBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Edit");
        editBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 67;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(15, 113, 0, 0);
        getContentPane().add(editBtn, gridBagConstraints);

        simpanBtn.setBackground(new java.awt.Color(20, 164, 77));
        simpanBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        simpanBtn.setForeground(new java.awt.Color(255, 255, 255));
        simpanBtn.setText("Simpan");
        simpanBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        simpanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.ipadx = 46;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(2, 166, 0, 0);
        getContentPane().add(simpanBtn, gridBagConstraints);

        LogoutBtn.setBackground(new java.awt.Color(220, 76, 100));
        LogoutBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        LogoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        LogoutBtn.setText("Log Out");
        LogoutBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        LogoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogoutBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 39;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 29, 0, 0);
        getContentPane().add(LogoutBtn, gridBagConstraints);

        judulBukuInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                judulBukuInputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 164;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 18, 0, 0);
        getContentPane().add(judulBukuInput, gridBagConstraints);

        pengarangInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pengarangInputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipadx = 164;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        getContentPane().add(pengarangInput, gridBagConstraints);

        penerbitInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                penerbitInputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 164;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 18, 0, 0);
        getContentPane().add(penerbitInput, gridBagConstraints);

        judulBukuLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        judulBukuLabel.setText("Judul Buku");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 15, 0, 0);
        getContentPane().add(judulBukuLabel, gridBagConstraints);

        kategoriLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        kategoriLabel.setText("Kategori");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 15, 0, 0);
        getContentPane().add(kategoriLabel, gridBagConstraints);

        pengarangLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        pengarangLabel.setText("Pengarang");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.gridheight = 5;
        gridBagConstraints.ipady = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 15, 0, 0);
        getContentPane().add(pengarangLabel, gridBagConstraints);

        penerbitLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        penerbitLabel.setText("Penerbit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 15, 0, 0);
        getContentPane().add(penerbitLabel, gridBagConstraints);

        isbnLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        isbnLabel.setText("ISBN");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(20, 35, 0, 0);
        getContentPane().add(isbnLabel, gridBagConstraints);

        isbnInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                isbnInputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 164;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 36, 0, 0);
        getContentPane().add(isbnInput, gridBagConstraints);

        stokLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        stokLabel.setText("Stok");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 35, 0, 0);
        getContentPane().add(stokLabel, gridBagConstraints);

        stokInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stokInputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridheight = 7;
        gridBagConstraints.ipadx = 164;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 36, 0, 0);
        getContentPane().add(stokInput, gridBagConstraints);

        kategoriInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridheight = 6;
        gridBagConstraints.ipadx = 155;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(17, 18, 0, 0);
        getContentPane().add(kategoriInput, gridBagConstraints);

        tahunTerbitLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        tahunTerbitLabel.setText("Tahun Terbit");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 35, 0, 0);
        getContentPane().add(tahunTerbitLabel, gridBagConstraints);

        tahunTerbitInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunTerbitInputActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridheight = 3;
        gridBagConstraints.ipadx = 164;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(13, 36, 0, 0);
        getContentPane().add(tahunTerbitInput, gridBagConstraints);

        userBtn.setBackground(new java.awt.Color(59, 113, 202));
        userBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        userBtn.setForeground(new java.awt.Color(255, 255, 255));
        userBtn.setText("User");
        userBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 11;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = 4;
        gridBagConstraints.ipadx = 62;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(21, 29, 0, 0);
        getContentPane().add(userBtn, gridBagConstraints);

        hapusBtn.setBackground(new java.awt.Color(220, 76, 100));
        hapusBtn.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        hapusBtn.setForeground(new java.awt.Color(255, 255, 255));
        hapusBtn.setText("Hapus");
        hapusBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        hapusBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 10;
        gridBagConstraints.gridy = 19;
        gridBagConstraints.gridheight = 2;
        gridBagConstraints.ipadx = 53;
        gridBagConstraints.ipady = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(16, 113, 0, 0);
        getContentPane().add(hapusBtn, gridBagConstraints);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseEntered

    private void stokInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_stokInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_stokInputActionPerformed

    private void tahunTerbitInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_tahunTerbitInputActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_tahunTerbitInputActionPerformed

    private void tambahBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:
        tambahData(judulBukuInput.getText(), kategoriInput.getSelectedItem().toString(),pengarangInput.getText(),penerbitInput.getText(),tahunTerbitInput.getText(),isbnInput.getText(),stokInput.getText());
    }// GEN-LAST:

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:

    }// GEN-LAST:

    private void simpanBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:

    }// GEN-LAST:

    private void hapusBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:

    }// GEN-LAST:

    private void purgeBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:

    }// GEN-LAST:

    private void LogoutBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:

    }// GEN-LAST:

    private void judulBukuInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:

    }

    private void pengarangInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:

    }

    private void penerbitInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:

    }

    private void kategoriBtnActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:

    }

    private void isbnInputActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager
                    .getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BukuCrudAdmin.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BukuCrudAdmin.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BukuCrudAdmin.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BukuCrudAdmin.class.getName()).log(
                    java.util.logging.Level.SEVERE, null,
                    ex);
        }
        // </editor-fold>
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BukuCrudAdmin().setVisible(true);
            }
        });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LogoutBtn;
    private javax.swing.JTable TabelBuku;
    private javax.swing.JButton editBtn;
    private javax.swing.JButton hapusBtn;
    private javax.swing.JTextField isbnInput;
    private javax.swing.JLabel isbnLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField judulBukuInput;
    private javax.swing.JLabel judulBukuLabel;
    private javax.swing.JButton kategoriBtn;
    private javax.swing.JComboBox<String> kategoriInput;
    private javax.swing.JLabel kategoriLabel;
    private javax.swing.JTextField penerbitInput;
    private javax.swing.JLabel penerbitLabel;
    private javax.swing.JTextField pengarangInput;
    private javax.swing.JLabel pengarangLabel;
    private javax.swing.JButton simpanBtn;
    private javax.swing.JTextField stokInput;
    private javax.swing.JLabel stokLabel;
    private javax.swing.JTextField tahunTerbitInput;
    private javax.swing.JLabel tahunTerbitLabel;
    private javax.swing.JButton tambahBtn;
    private javax.swing.JButton userBtn;
    // End of variables declaration//GEN-END:variables
}
